import type { NextPage } from 'next';
import Head from 'next/head';

import { api } from '~/utils/api';
const Home: NextPage = () => {
    const randomNumberQuery = api.random.number.useQuery();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen flex-col items-center bg-black text-white">
                <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
                    <h1 className="text-5xl flex flex-col w-max font-extrabold tracking-tight sm:text-[5rem] m-auto">
                        <div>
                            Random{' '}
                            <span className="text-rose-600 mr-2">number</span>?
                        </div>
                        <div className="mx-auto">{randomNumberQuery.data}</div>
                    </h1>
                    <button
                        className="bg-rose-600 text-white font-bold py-2 px-4 rounded shadow-2xl shadow-rose-600"
                        onClick={() => randomNumberQuery.refetch()}
                    >
                        Refresh
                    </button>
                </div>
            </main>
        </>
    );
};

export default Home;
